<a href="https://colab.research.google.com/github/MiguelVargaszzz/ClaseInteligenciaArtificial/blob/main/EDA_Apuntes_de_Clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Crear un dataset simulado
np.random.seed(42)
data = {
    "Estudiante": [f"Estudiante{i}" for i in range(1, 21)],
    "Edad": np.random.randint(18, 25, size=21),
    "Genero": np.random.choice(["Masculino", "Femenino"], size=20),
    "Nota_matematicas": np.random.normal(70, 10, size=20).round(1),
    "Nota_Ciencias": np.random.normal(75, 12, size=20).round(1),
    "Nota_Ingles": np.random.normal(65, 15, size=20).round(1),
}

df = pd.DataFrame(data)



#Ejercicios con numpy
**Crear el arreglo**

*cursiva*
## subtitulo

$a=\frac{5^n}{x^{2+i}}$

![imagen](https://images7.memedroid.com/images/UPLOADED896/65454f4d1c061.jpeg)

$A=x^{(t)}$

Pandas para cuando son arreglos de datos que tienen diferentes tipos
cuando son del mismo tipo numpy


In [ ]:
# prompt: crear un arreglo con la variable datos, con datos sintetico, usando numpy donde la columna 0, sea la edad y la columna 1 sea la notas de IA que van de 0 a 5

import numpy as np

# Crear un arreglo con datos sintéticos usando NumPy
num_estudiantes = 20
edades = np.random.randint(18, 25, size=num_estudiantes)
notas_ia = np.random.uniform(0, 5, size=num_estudiantes).round(2)  # Notas de IA entre 0 y 5

datos = np.column_stack((edades, notas_ia))

datos


array([[22.  ,  3.17],
       [24.  ,  0.12],
       [19.  ,  3.53],
       [21.  ,  4.82],
       [20.  ,  1.22],
       [24.  ,  3.5 ],
       [18.  ,  4.13],
       [24.  ,  0.14],
       [23.  ,  0.47],
       [22.  ,  3.86],
       [19.  ,  0.45],
       [21.  ,  4.53],
       [22.  ,  1.98],
       [20.  ,  1.77],
       [22.  ,  4.65],
       [21.  ,  3.29],
       [19.  ,  3.69],
       [21.  ,  4.68],
       [24.  ,  1.12],
       [23.  ,  0.73]])

In [ ]:
# Calcular el promedio de la columna 'Edad' (columna 0 en el array 'datos')
promedio_edades = np.mean(datos[:, 1])
print(f"El promedio de edades es: {promedio_edades}")


El promedio de edades es: 2.5925


In [ ]:
type(datos)

numpy.ndarray

In [ ]:
datos[0:5,0]

array([22., 24., 19., 21., 20.])

In [ ]:
datos[4:6,-1]

array([1.22, 3.5 ])

In [ ]:
datos[4:6,:]

array([[20.  ,  1.22],
       [24.  ,  3.5 ]])

In [ ]:
datos[4:6,1]

array([1.22, 3.5 ])

In [ ]:
datos[4:6,0]

array([20., 24.])

In [ ]:
identidad=np.eye(8,8)
print(identidad)
3+5

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
identidad.shape, datos.shape

((8, 8), (20, 2))

In [ ]:
nombres = np.array([
    "Juan Camilo", "Sofia", "David", "Valentina", "Sebastian",
    "Maria Camila", "Daniel", "Laura", "Alejandro", "Gabriela",
    "Santiago", "Isabella", "Nicolas", "Juliana", "Miguel",
    "Salome", "Mateo", "Luciana", "Samuel", "Emma"
])
nombres

array(['Juan Camilo', 'Sofia', 'David', 'Valentina', 'Sebastian',
       'Maria Camila', 'Daniel', 'Laura', 'Alejandro', 'Gabriela',
       'Santiago', 'Isabella', 'Nicolas', 'Juliana', 'Miguel', 'Salome',
       'Mateo', 'Luciana', 'Samuel', 'Emma'], dtype='<U12')

In [ ]:
import pandas as pd
# Crear el DataFrame 'alumnos'
alumnos = pd.DataFrame({
    'Nombre': nombres,
    'Edad': edades,
    'Nota_IA': notas_ia
})

alumnos


Nombre  Edad  Nota_IA
0    Juan Camilo    22     3.17
1          Sofia    24     0.12
2          David    19     3.53
3      Valentina    21     4.82
4      Sebastian    20     1.22
5   Maria Camila    24     3.50
6         Daniel    18     4.13
7          Laura    24     0.14
8      Alejandro    23     0.47
9       Gabriela    22     3.86
10      Santiago    19     0.45
11      Isabella    21     4.53
12       Nicolas    22     1.98
13       Juliana    20     1.77
14        Miguel    22     4.65
15        Salome    21     3.29
16         Mateo    19     3.69
17       Luciana    21     4.68
18        Samuel    24     1.12
19          Emma    23     0.73

In [ ]:
alumnos.shape

(20, 3)

In [ ]:
type(alumnos)

pandas.core.frame.DataFrame

In [ ]:
alumnos.dtypes

Nombre      object
Edad         int64
Nota_IA    float64
dtype: object

In [ ]:
alumnos.Edad.mean()

21.45

In [ ]:
alumnos["Edad"].mean()

21.45