<a href="https://colab.research.google.com/github/MiguelVargaszzz/ClaseInteligenciaArtificial/blob/main/EDA_Apuntes_de_Clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejercicios con numpy
**Crear el arreglo**

*cursiva*
## subtitulo

$a=\frac{5^n}{x^{2+i}}$

![imagen](https://images7.memedroid.com/images/UPLOADED896/65454f4d1c061.jpeg)

$A=x^{(t)}$

Pandas para cuando son arreglos de datos que tienen diferentes tipos
cuando son del mismo tipo numpy


In [5]:
# prompt: crear un arreglo con la variable datos, con datos sintetico, usando numpy donde la columna 0, sea la edad y la columna 1 sea la notas de IA que van de 0 a 5

import numpy as np

# Crear un arreglo con datos sintéticos usando NumPy
num_estudiantes = 20
edades = np.random.randint(18, 25, size=num_estudiantes)
notas_ia = np.random.uniform(0, 5, size=num_estudiantes).round(2)  # Notas de IA entre 0 y 5

datos = np.column_stack((edades, notas_ia))

datos


array([[24.  ,  2.28],
       [24.  ,  1.09],
       [22.  ,  2.08],
       [24.  ,  4.42],
       [20.  ,  1.62],
       [22.  ,  0.61],
       [21.  ,  1.78],
       [22.  ,  4.53],
       [24.  ,  1.36],
       [20.  ,  3.24],
       [20.  ,  0.  ],
       [23.  ,  1.76],
       [21.  ,  1.52],
       [19.  ,  0.82],
       [19.  ,  2.67],
       [22.  ,  2.42],
       [23.  ,  3.46],
       [18.  ,  1.35],
       [22.  ,  1.22],
       [23.  ,  0.84]])

In [6]:
# Calcular el promedio de la columna 'Edad' (columna 0 en el array 'datos')
promedio_edades = np.mean(datos[:, 1])
print(f"El promedio de edades es: {promedio_edades}")


El promedio de edades es: 1.9535000000000005


In [7]:
type(datos)

numpy.ndarray

In [8]:
datos[0:5,0]

array([24., 24., 22., 24., 20.])

In [9]:
datos[4:6,-1]

array([1.62, 0.61])

In [10]:
datos[4:6,:]

array([[20.  ,  1.62],
       [22.  ,  0.61]])

In [11]:
datos[4:6,1]

array([1.62, 0.61])

In [14]:
datos[4:6,0]

array([20., 22.])

In [13]:
identidad=np.eye(8,8)
print(identidad)
3+5

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


8

In [16]:
identidad.shape, datos.shape

((8, 8), (20, 2))

In [15]:
nombres = np.array([
    "Juan Camilo", "Sofia", "David", "Valentina", "Sebastian",
    "Maria Camila", "Daniel", "Laura", "Alejandro", "Gabriela",
    "Santiago", "Isabella", "Nicolas", "Juliana", "Miguel",
    "Salome", "Mateo", "Luciana", "Samuel", "Emma"
])
nombres

array(['Juan Camilo', 'Sofia', 'David', 'Valentina', 'Sebastian',
       'Maria Camila', 'Daniel', 'Laura', 'Alejandro', 'Gabriela',
       'Santiago', 'Isabella', 'Nicolas', 'Juliana', 'Miguel', 'Salome',
       'Mateo', 'Luciana', 'Samuel', 'Emma'], dtype='<U12')

In [17]:
import pandas as pd
# Crear el DataFrame 'alumnos'
alumnos = pd.DataFrame({
    'Nombre': nombres,
    'Edad': edades,
    'Nota_IA': notas_ia
})

alumnos


Nombre  Edad  Nota_IA
0    Juan Camilo    24     2.28
1          Sofia    24     1.09
2          David    22     2.08
3      Valentina    24     4.42
4      Sebastian    20     1.62
5   Maria Camila    22     0.61
6         Daniel    21     1.78
7          Laura    22     4.53
8      Alejandro    24     1.36
9       Gabriela    20     3.24
10      Santiago    20     0.00
11      Isabella    23     1.76
12       Nicolas    21     1.52
13       Juliana    19     0.82
14        Miguel    19     2.67
15        Salome    22     2.42
16         Mateo    23     3.46
17       Luciana    18     1.35
18        Samuel    22     1.22
19          Emma    23     0.84

In [18]:
alumnos.shape

(20, 3)

In [19]:
type(alumnos)

pandas.core.frame.DataFrame

In [20]:
alumnos.dtypes

Nombre      object
Edad         int64
Nota_IA    float64
dtype: object

In [21]:
alumnos.Edad.mean()

21.65

In [22]:
alumnos["Edad"].mean()

21.65

In [23]:
alumnos.Nota_IA.max()

4.53

In [24]:
alumnos[alumnos.Nota_IA>= 3.5]

Nombre  Edad  Nota_IA
3  Valentina    24     4.42
7      Laura    22     4.53

In [30]:
alumnos[alumnos.Nombre=="Sofia"]

Nombre  Edad  Nota_IA
1  Sofia    24     1.09